# Generated by Django 3.0.8 on 2020-09-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0002_auto_20200916_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
        migrations.CreateModel(
            name='img_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe.Recipe')),
            ],
        ),
    ]
