# Generated by Django 3.0.8 on 2020-09-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_auto_20200917_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='price',
            field=models.IntegerField(),
        ),
    ]
