# Generated by Django 3.0.8 on 2020-09-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_auto_20200921_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
