# Generated by Django 3.0.8 on 2020-09-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0003_auto_20200917_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='img_url',
        ),
    ]
